CREATE DATABASE BATTLE_SHIP
GO

USE BATTLE_SHIP;
GO

-- 1. Bảng Người Dùng
CREATE TABLE NguoiDung
(
	Id INT IDENTITY(1,1) NOT NULL,
	TenDangNhap VARCHAR(100) NOT NULL,
	MatKhau VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NULL,	
	NgayTao DATETIME NOT NULL
		CONSTRAINT DF_NguoiDung_NgayTao DEFAULT CURRENT_TIMESTAMP,
	ResetCode VARCHAR(10) NULL,
	ResetCodeExpire DATETIME NULL,
	LastOnline DATETIME NULL,

	CONSTRAINT PK_Nguoidung PRIMARY KEY (Id),
	CONSTRAINT UQ_Nguoidung_TenDangNhap UNIQUE (TenDangNhap)
);
GO

-- 2. Bảng Phòng Chờ
CREATE TABLE PhongCho
(
	Id INT IDENTITY(1,1) NOT NULL,
	IdChuPhong INT NOT NULL,
	IDKhach INT NULL,
	TrangThai VARCHAR(20) NOT NULL
		CONSTRAINT DF_PhongCho_TrangThai DEFAULT 'waiting'
		CONSTRAINT CK_PhongCho_TrangThai CHECK
			(TrangThai IN ('waiting', 'full', 'playing', 'empty')),
	NgayTao DATETIME NOT NULL
		CONSTRAINT DF_PhongCho_NgayTao DEFAULT GETDATE(),

	CONSTRAINT PK_PhongCho PRIMARY KEY (Id),
	CONSTRAINT FK_PhongCho_NguoiDung_IdChuPhong
		FOREIGN KEY (IdChuPhong) REFERENCES NguoiDung(Id),
	CONSTRAINT FK_PhongCho_NguoiDung_IDKhach
		FOREIGN KEY (IDKhach) REFERENCES NguoiDung(Id)
);
GO

-- 3. Bảng Trận Đấu
CREATE TABLE TranDau
(
	Id INT IDENTITY(1,1) NOT NULL,
	IdPlayer1 INT NOT NULL,
	IdPlayer2 INT NOT NULL,
	TenNV1 NVARCHAR(50) NOT NULL,
	TenNV2 NVARCHAR(50) NOT NULL,
	KichThuoc INT NOT NULL
		CONSTRAINT CK_TranDau_KichThuoc CHECK
			(KichThuoc IN (8, 9, 10)),
	Winner INT NULL,
	TimeStart DATETIME NOT NULL
		CONSTRAINT DF_TranDau_TimeStart DEFAULT CURRENT_TIMESTAMP,
	TimeEnd DATETIME NULL,
	IdPhongCho INT NOT NULL,

	CONSTRAINT PK_TranDau PRIMARY KEY (Id),
	CONSTRAINT FK_TranDau_NguoiDung_Player1
		FOREIGN KEY (IdPlayer1) REFERENCES NguoiDung(Id),
	CONSTRAINT FK_TranDau_NguoiDung_Player2
		FOREIGN KEY (IdPlayer2) REFERENCES NguoiDung(Id),
	CONSTRAINT FK_TranDau_NguoiDung_Winner
		FOREIGN KEY (Winner) REFERENCES NguoiDung(Id),
	CONSTRAINT FK_TranDau_PhongCho_IdPhongCho
		FOREIGN KEY (IdPhongCho) REFERENCES PhongCho(Id)
);
GO

-- 4. Bảng Tin Nhắn
CREATE TABLE TinNhan
(
	Id INT IDENTITY(1,1) NOT NULL,
	IdTranDau INT NULL,
	IdPhongCho INT NULL,
	IDNguoiDung INT NOT NULL,
	NoiDung NVARCHAR(100) NOT NULL,
	ThoiGian DATETIME NOT NULL
		CONSTRAINT DF_TinNhan_ThoiGian DEFAULT CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_TinNhan PRIMARY KEY (Id),
	CONSTRAINT FK_TinNhan_TranDau_IdTranDau
		FOREIGN KEY (IdTranDau) REFERENCES TranDau(Id),
	CONSTRAINT FK_TinNhan_PhongCho_IdPhongCho
		FOREIGN KEY (IdPhongCho) REFERENCES PhongCho(Id),
	CONSTRAINT CK_TinNhan_TonTaiViTriGui CHECK
		(IdTranDau IS NOT NULL OR IdPhongCho IS NOT NULL),
	CONSTRAINT FK_TinNhan_NguoiDung_IdNguoiDung
		FOREIGN KEY (IdNguoiDung) REFERENCES NguoiDung(Id)
);
GO

-- 5. Bảng Bảng Xếp Hạng
CREATE TABLE BangXepHang
(
	Id INT IDENTITY(1,1) NOT NULL,
	IdNguoiDung INT NOT NULL,
	SoTranThang INT NOT NULL
		CONSTRAINT DF_BangXepHang_SoTranThang DEFAULT 0
		CONSTRAINT CK_BangXepHang_SoTranThang CHECK (SoTranThang >= 0),
	SoTranThua INT NOT NULL
		CONSTRAINT DF_BangXepHang_SoTranThua DEFAULT 0
		CONSTRAINT CK_BangXepHang_SoTranThua CHECK (SoTranThua >= 0),
	CapSao INT NOT NULL
		CONSTRAINT DF_BangXepHang_CapSao DEFAULT 0
		CONSTRAINT CK_BangXepHang_CapSao CHECK (CapSao >= 0),

	CONSTRAINT PK_BangXepHang PRIMARY KEY (Id),
	CONSTRAINT FK_BangXepHang_NguoiDung_IdNguoiDung
		FOREIGN KEY (IdNguoiDung) REFERENCES NguoiDung(Id),
	CONSTRAINT UQ_BangXepHang_IdNguoiDung UNIQUE (IdNguoiDung)
);
GO

-- 6. Bảng Bạn Bè
CREATE TABLE BanBe
(
	IdNguoi1 INT NOT NULL,
	IdNguoi2 INT NOT NULL,
	TrangThai VARCHAR(10) NOT NULL
		CONSTRAINT DF_BanBe_TrangThai DEFAULT 'PENDING'
		CONSTRAINT CK_BanBe_TrangThai CHECK
			(TrangThai IN ('PENDING', 'ACCEPTED', 'BLOCK')),
	IdNguoiThucHien INT NOT NULL,
	
	CONSTRAINT PK_BanBe PRIMARY KEY (IdNguoi1, IdNguoi2),
	CONSTRAINT FK_BanBe_NguoiDung_IdNguoi1
		FOREIGN KEY (IdNguoi1) REFERENCES NguoiDung(Id),
	CONSTRAINT FK_BanBe_NguoiDung_IdNguoi2
		FOREIGN KEY (IdNguoi2) REFERENCES NguoiDung(Id),
	CONSTRAINT FK_BanBe_NguoiDung_IdNguoiThucHien
		FOREIGN KEY (IdNguoiThucHien) REFERENCES NguoiDung(Id),
	CONSTRAINT CK_BanBe_IdNguoi1_IdNguoi2 CHECK
		(IdNguoi1 < IdNguoi2)
);
GO
